language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  TEST_OUTPUT_STYLE: 'pretty'
  PHPCS_REPORT_STYLE: 'full'
  COMPOSER_OPTIONS: '--optimize-autoloader'

sudo: false

matrix:
  include:
  - php: '7.0'
    env: CI_ONLY_SYMFONY_EXTENSION=true
  - php: '7.1'
    env: CI_ONLY_SYMFONY_EXTENSION=true
  - php: '7.2'
    env: CI_ONLY_SYMFONY_EXTENSION=true
  fast_finish: true

install:
  - make build
script:
  - make test-technical
  - make test-functional

cache:
  directories:
    - $HOME/.composer
    - vendor
