language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  CI: 'true'
  TEST_OUTPUT_STYLE: 'pretty'
  PHPCS_REPORT_STYLE: 'full'
  COMPOSER_OPTIONS: '--optimize-autoloader'
  CI_ONLY_SYMFONY_EXTENSION: true
  CI_ONLY_SYMFONY_EXTENSION: false

sudo: false

matrix:
  fast_finish: true

install:
  - make build
script:
  - make test-technical
  - make test-functional

cache:
  directories:
    - $HOME/.composer
    - vendor
