coverage:
  range: "80...100"

flags:
  nightly:
    joined: false

comment:
  show_carryforward_flags: true

github_checks:
  annotations: true

fixes:
   - "/home/runner/work/php-jsonrpc-server-sdk/php-jsonrpc-server-sdk/::"
