name: TODO
description: TODO

inputs:
  path:
    description: A group directory or a glob pattern in order to find group directories and merge their metadata
    required: true
  token:
    description: Codecov upload token
    required: true
  follow-symbolic-links:
    description: |
      Indicates whether to follow symbolic links when resolving `path`
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Make action inputs available for actions/github-script scripts
      uses: actions/github-script@v7
      env:
        INPUT_MAP: ${{ toJson(inputs) }}
      with:
        script: |
          Object.entries(JSON.parse(process.env.INPUT_MAP)).forEach(([key, value]) => {
            const envName = 'INPUT_' + key.replace(/ /g, '_').toUpperCase();
            core.debug(`Promote ${key} input as ${envName} env var. value='${value}'`);
            core.exportVariable(envName, value);
          });

    - uses: actions/github-script@v7
      with:
        script: |
          core.info('Validate required inputs');
          
          core.getInput('path', {required: true});
          core.getInput('token', {required: true});

    # @TODO move reports-group/load-metadata action to a dedicated repo and remove the checkout
    - uses: actions/checkout@v4
      with:
        path: custom-action-repo

    - id: load-metadata
      uses: ./custom-action-repo/.github/actions/load-metadata
      with:
        path: ${{ inputs.path }}
        format: string # String in order to concatenate interesting values
        glue-string: ',' # Ensure glue string as it's the expected one by the uploader
        follow-symbolic-links: ${{ inputs.follow-symbolic-links }}

    - id: build-uploader-options
      uses: actions/github-script@v7
      env:
        METADATA: ${{ steps.load-metadata.outputs.metadata }}
      with:
        script: |
          core.info('Build uploader options');
          const {METADATA} = process.env;
          
          const metadata = JSON.parse(METADATA);
          core.setOutput('name', metadata.name);
          core.setOutput('files', metadata.reportPaths);
          if (metadata.flags.length > 0) {
            core.setOutput('flags', metadata.flags);
          }
          

    - if: ${{ '' == steps.build-uploader-options.outputs.files }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed('Unable to retrieve any report to upload. Something wrong most likely happened !');

    - id: upload
      uses: codecov/codecov-action@v4
      with:
        token: ${{ inputs.token }}
        name: ${{ steps.build-uploader-options.outputs.name }}
        files: ${{ steps.build-uploader-options.outputs.files }}
        flags: ${{ steps.build-uploader-options.outputs.flags }}
        # underlying CLI behavior
        disable_search: true
        # GHAction behavior
        fail_ci_if_error: true
        verbose: ${{ runner.debug == '1' }}
