name: find
description: |
  Find reports group directory under the provided `path`
inputs:
  path:
    description: A group directory or a glob pattern in order to find group directories and merge their metadata
    required: true
  format:
    description: |
      `string` (default) or `json`
    required: true
    default: 'string'
  glue-string:
    description: String used to concatenate values when 'string' format is used
    required: true
    default: ','
  follow-symbolic-links:
    description: Indicates whether to follow symbolic links when resolving `path`
    required: true
    default: 'false'
outputs:
  list:
    description: |
      List of group paths separated by `glue-string` with `string` format. Or a JSON encoded list with `json` format

runs:
  using: 'node20'
  main: 'dist/index.js'
