name: find
description: |
  Find reports group directory under the provided `path`
inputs:
  path:
    description: A group directory, or a glob pattern in order to find underlying group directories
    required: true
  follow-symbolic-links:
    description: Indicates whether to follow symbolic links when resolving `path`
    required: false
    default: 'false'
outputs:
  list:
    description: Glob compatible list of reports group directory path (=multiline list of paths)

runs:
  using: 'node20'
  main: 'dist/index.js'
