name: TODO
description: TODO

inputs:
  from-triggering-workflow:
    description: |
      Whether to look for triggering workflow context or just current workflow context (default `true` !).
       - True: In case current workflow event is `workflow_run`, the context of the workflow which **triggered** the current one will be returned. Else returns the current workflow context
       - False: Return the context for the current workflow.
    required: false
    default: 'true'

outputs:
  repository-owner:
    description: Owner of the repository
  repository-name:
    description: Name of the repository
  commit-sha:
    description: |
      Full commit SHA.
      - `push` event => Branch where the push happened
      - `pull_request` event => Head branch name
      - `workflow_run` event => Commit upon which the triggering workflow has been executed (should match behaviors described on other cases then)
      - Other events => Fallback on `github.sha` value
  branch:
    description: |
      Branch name
      - `push` event => latest commit pushed
      - `pull_request` event => latest commit pushed on the pull request
      - `workflow_run` event => Branch where the triggering workflow has been executed (should match behaviors described on other cases then)
      - Other events => Fallback on `github.ref` value if it's a branch ref, else the repository default branch is returned
  pull-request:
    description: Pull request number. Available only in case of `pull_request` event !
  is-pr-from-fork:
    description: Weither PR head is outside of current repository. Obviously accurate only in case of `pull_request` event !
  workflow-name:
    description: Name of the workflow, either current one or the triggering one (based on `from-triggering-workflow` value).
  run-id:
    description: Workflow run ID, either current one or the triggering one (based on `from-triggering-workflow` value).
  server-url:
    description: Server url. Usually `https://github.com` but may be different in case of self-hosted GitHub server!
  workflow-run-url:
    description: Url to the workflow execution page


runs:
  using: 'node20'
  main: 'dist/index.js'
