name: TODO
description: TODO

inputs:
  token:
    description: Codecov token
    required: true
  path:
    description: Group directory path
    required: true

outputs:
  result:
    description: TODO
    value: ${{ steps.upload.outputs.result }}
  matrix:
    description: TODO # Matrix of artifacts along with their group reports metadata
    value: ${{ steps.main.outputs.matrix }}
  reports:
    description: TODO # Map of reports indexed by artifact name
    value: ${{ steps.main.outputs.reports }}

runs:
  using: "composite"
  steps:
    - name: Build uploader options
      id: build-options
      uses: actions/github-script@v7
      env:
        PATH: ${{ inputs.path }}
      with:
        script: |
          const fs = require('fs');
          const { PATH } = process.env;
          
          const metadata = JSON.parse(fs.readFileSync(`${PATH}/.coverage-reports-metadata.json`));

          core.setOutput("name", metadata.name);
          core.setOutput("files", metadata.reports.map(f => `${PATH}/${f}`).join(','));
          core.setOutput("flags", metadata.flags.join(','));

    - name: Upload group reports
      if: ${{ '' != steps.build-options.outputs.files }}
      uses: codecov/codecov-action@v4
      with:
        token: ${{ inputs.token }}
        name: ${{ steps.build-options.outputs.name }}
        files: ${{ steps.build-options.outputs.files }}
        flags: ${{ steps.build-options.outputs.flags }}
        # underlying CLI behavior
        disable_search: true
        # GHAction behavior
        fail_ci_if_error: true
        verbose: ${{ runner.debug == '1' }}

    - name: No report error
      if: ${{ '' == steps.build-options.outputs.files }}
      uses: actions/github-script@v7
      with:
        script: core.setFailed('Unable to retrieve any report for the group. Something wrong most likely happened !');
