name: 'Codacy upload'
on:
  workflow_call:
    inputs:
      artifacts-pattern:
        required: true
        type: string
    secrets:
      PROJECT_TOKEN:
        required: true
    outputs:
      info:
        description: TODO
        value: ${{ jobs.main.outputs.info }}
      matrix:
        description: TODO
        value: ${{ jobs.main.outputs.matrix }}
      reports:
        description: TODO
        value: ${{ jobs.main.outputs.reports }}

jobs:
  main:
    name: Upload
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_PATH: coverage-reports
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifacts-pattern }}
          path: ${{ env.ARTIFACTS_PATH }}

      - name: Build metadata
        id: build-metadata
        run: |
          FILES=$(find ./coverage-reports -type f -name "report-*" | tr "\n" ",")
          echo "info::files='$FILES'"
          echo "files=$FILES" >> "$GITHUB_OUTPUT"

      - name: Upload
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          coverage-reports: ${{ steps.build-metadata.outputs.files }}
          project-token: ${{ secrets.PROJECT_TOKEN }}
