name: 'Codacy upload'
on:
  workflow_call:
    inputs:
      artifacts-pattern:
        required: true
        type: string
    secrets:
      PROJECT_TOKEN:
        required: true

jobs:
  main:
    name: Upload reports
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifacts-pattern }}
          path: coverage-reports

      - name: Build metadata
        id: build-metadata
        run: |
          FILES=$(find ./coverage-reports -type f -name "report-*" | tr "\n" ",")
          echo "::debug::files='$FILES'"
          echo "files=$FILES" >> "$GITHUB_OUTPUT"

      - name: Upload
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          coverage-reports: ${{ steps.build-metadata.outputs.files }}
          project-token: ${{ secrets.PROJECT_TOKEN }}
