name: 'Codecov upload'
on:
  workflow_call:
    inputs:
      artifacts-pattern:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      info: ${{ steps.fetch-info.outputs.info }}
      matrix: ${{ steps.fetch-info.outputs.matrix }}
      reports: ${{ steps.fetch-info.outputs.reports }}
    steps:
      # @TODO move coverage-reports-metadata-from-artifacts action to a dedicated repo and remove the checkout
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifacts-pattern }}
          path: ${{ runner.temp }}/coverage-reports

      - name: Fetch info
        id: fetch-info
        uses: ./.github/actions/coverage-reports-metadata-from-artifacts
        with:
          root: ${{ runner.temp }}/coverage-reports

  upload:
    name: Upload ${{ matrix.name }} reports
    runs-on: ubuntu-latest
    needs: [ prepare ]
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      # @TODO remove the checkout and fill right values directly (sha, branch, pr, etc)
      - name: Check out code # Mostly to retrieve codecov config file and to figure out some stuff automatically
        uses: actions/checkout@v3

      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: coverage-reports

      - name: Build metadata
        id: build-metadata
        uses: actions/github-script@v7
        env:
          PATH: ${{ matrix.path }}
          REPORTS: ${{ matrix.reports }}
          FLAGS: ${{ matrix.flags }}
        with:
          script: |
            const { PATH, REPORTS, FLAGS } = process.env;

            core.setOutput("files", JSON.parse(REPORTS).map(f => `coverage-reports/${PATH}/${f}`).join(','));
            core.setOutput("flags", JSON.parse(FLAGS).join(','));

      - name: Upload
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ matrix.name }}
          files: ${{ steps.build-metadata.outputs.files }}
          flags: ${{ steps.build-metadata.outputs.flags }}
          disable_search: true
          fail_ci_if_error: true
          verbose: ${{ runner.debug == '1' }}
