name: Dependabot PRs
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  job:
    name: ".github"
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'yoanm/php-jsonrpc-server-sdk'
    permissions:
      contents: write
      pull-requests: write
    uses: yoanm/.github/.github/workflows/reusable-dependabot-PRs-manager.yml@v1
    with:
      label: 'with-nightly-tests'
