name: 'Nightly reusable workflow'

on:
  workflow_call:
    inputs:
      ref:
        description: Reference in order to fetch code
        type: string
        required: false
        default: "${{ github.event.workflow_run && github.event.workflow_run.referenced_workflows[0] && github.event.workflow_run.referenced_workflows[0].ref || github.ref }}"

env:
  COMPOSER_PREFER_STABLE: '1'
  TEST_OUTPUT_STYLE: pretty

permissions:
  contents: read
  checks: write # For the check run creation !

jobs:
  tests:
    name: PHP
    permissions:
      contents: read
      checks: write # For the check run creation !
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      COMPOSER_IGNORE_PLATFORM_REQ: 'php+'
    steps:
      - name: 'Check run ○'
        uses: yoanm/temp-reports-group-workspace/utils/attach-check-run-to-triggering-workflow@v0
        with:
          name: 'Nightly / PHP'
          fails-on-triggering-workflow-failure: true

      - name: Fetch PHP supported versions
        id: fetch-php-versions
        uses: yoanm/gha-supported-versions-parser@feature/init
        with:
          dependency: php
          path: .github/workflows/supported-versions.json
          ref: "${{ inputs.ref }}"

      - name: Check out code
        uses: actions/checkout@v5
        with:
          ref: "${{ inputs.ref }}"

      - name: Setup PHP ${{ steps.fetch-php-versions.outputs.next }}
        id: setup-php
        uses: shivammathur/setup-php@v2
        env:
          update: true # whether to use latest available patch for the version or not
          fail-fast: true # step will fail if an extension or tool fails to set up
        with:
          php-version: ${{ steps.fetch-php-versions.outputs.next }}
          tools: composer
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Setup cache for PHP ${{ steps.setup-php.outputs.php-version }}
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          # Clear the cache if composer.json (as composer.lock is not available) has been updated
          key: tests-php${{ steps.setup-php.outputs.php-version }}-${{ hashFiles('composer.json') }}

      - name: Build with PHP ${{ steps.setup-php.outputs.php-version }}
        run: make build

      - name: Test
        run: make test-unit && make test-functional
