name: 'Supported versions auto-update'

on:
  workflow_dispatch: # Allows to run the workflow manually from the Actions tab
  schedule:
    - cron: '0 0 1 * *' # Every month

permissions:
  contents: write
  issues: write

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  COMMIT_AUTHOR_NAME: github-actions
  COMMIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  V_FILE: .supported-versions.json
  SERVER_URL: ${{ github.server_url }}
  REPO_NAME: ${{ github.repository }}
  RUN_ID: ${{ github.run_id }}

jobs:
  php:
    name: PHP
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    env:
      UPDATE_BRANCH: auto/feature/update-php-supported-version
      UPDATE_TITLE: "Update PHP supported versions"
      ISSUE_ASSIGNEE: "yoanm"
      PR_LABELS: "with-nightly-tests"
    steps:
      - name: "Checkout current repository"
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Create/Switch to update branch
        env:
          BRANCH: ${{ env.UPDATE_BRANCH }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          git checkout "${BRANCH}" || git checkout --track origin/${DEFAULT_BRANCH} -b "${BRANCH}"

      - name: Update versions
        id: update-versions
        uses: yoanm/gha-php-supported-versions-auto-update@v0
        with:
          path: ${{ env.V_FILE }}

      - name: "Add / commit / push"
        id: commit-and-push
        if: ${{ steps.update-versions.outputs.updated == '1' }}
        run: |
          git config user.name "${{ env.COMMIT_AUTHOR_NAME }}"
          git config user.email "${{ env.COMMIT_AUTHOR_EMAIL }}"
          git add ${{ env.V_FILE }}
          if [ $(git diff --cached --name-only | wc -l) -gt 0 ]; then
            echo "Pushing updated files:"
            git diff --cached --color ${{ env.V_FILE }}
            git commit -m "${{ env.UPDATE_TITLE }} ($(date +'%Y-%m-%d'))" -m "See ${{ env.SERVER_URL }}/${{ env.REPO_NAME }}/actions/runs/${{ env.RUN_ID }}";
            git push --set-upstream origin "${{ env.UPDATE_BRANCH }}";
            ISSUE_NEEDED=1
          else
            echo "Nothing to commit !";
            ISSUE_NEEDED=0
          fi;

          echo "issue-needed=${ISSUE_NEEDED}" >> $GITHUB_OUTPUT

      - name: "Create issue"
        if: ${{ steps.commit-and-push.outputs.issue-needed == 1 }}
        env:
          ISSUE_TITLE: "[AUTO] ${{ env.UPDATE_TITLE }}"
          PR_TITLE: ${{ env.UPDATE_TITLE }}
          BODY_FILE: ${{ runner.temp }}/body-file.txt
          GH_TOKEN: ${{ github.token }}
        run: |
          ISSUE_BODY_HEADER="Supported versions file needs to be updated !"
          ISSUE_URL=$(gh issue list --search "state:open author:@me \"${{ env.ISSUE_TITLE }}\"" --json url --jq '.[0].url')
          if [[ -z "${ISSUE_URL}" ]]; then
            # In order to create the PR with a body stating that it fixes the newly created issue, the issue id is required !
            # => First create the issue, then retrieve its id and create the proper link to create the PR
          
            echo "Creating new issue"
            gh issue create --title "${{ env.ISSUE_TITLE }}" --body "${ISSUE_BODY_HEADER}" --assignee "${{ env.ISSUE_ASSIGNEE }}" > issue_url.txt
            
            ISSUE_URL=$(cat issue_url.txt)
            if [[ -z "${ISSUE_URL}" ]]; then
              echo "::error::Unable to retrieve the issue URL !"
              exit 1
            fi
            ISSUE_ID=$(gh issue view "${ISSUE_URL}" --json number --jq '.number')
            if [[ -z "${ISSUE_ID}" ]]; then
              echo "::error::Unable to retrieve the issue ID !"
              exit 1
            fi
            
            echo "Update issue with proper link to create the PR"
            PR_ENCODED_TITLE=$(jq -rn --arg x "${{ env.PR_TITLE }}" '$x|@uri')
            PR_BODY_ENCODED=$(jq -rn --arg x "Fix #${ISSUE_ID}" '$x|@uri')
            echo "${ISSUE_BODY_HEADER}" > ${{ env.BODY_FILE }}
            echo "" >> ${{ env.BODY_FILE }}
            echo "Create PR [there](https://github.com/${{ env.REPO_NAME }}/compare/${{ env.UPDATE_BRANCH }}?quick_pull=1&assignees=${{ env.ISSUE_ASSIGNEE }}&labels=${{ env.PR_LABELS }}&title=${PR_ENCODED_TITLE}&body=${PR_BODY_ENCODED})" >> ${{ env.BODY_FILE }}

            gh issue edit "${ISSUE_URL}" --body-file "${{ env.BODY_FILE }}"
          else
            echo "Issue already exists: ${ISSUE_URL}"
          fi
