.PHONY: install
install:
	@echo "Nothing to install !"

.PHONY: build
build:
	@echo "Nothing to build !"

.PHONY: package
package:
	@echo "Nothing to pack !"

.PHONY: lint
lint:
	@echo "Nothing to lint !"

.PHONY: test
test:
	@echo "Nothing to test !"
