name: TODO
description: TODO

inputs:
  path:
    description: A group directory or a glob pattern in order to find group directories and merge their metadata
    required: true
  format:
    description: string (default) or json
    default: 'string'
  glue-string:
    description: String used to concatenate values when 'string' format is used (default to comma)
    default: ','
  follow-symbolic-links:
    description: |
      Indicates whether to follow symbolic links when resolving `path`
    default: 'true'

outputs:
  # @TODO Re-add individual properties since toJson() doesn't seem available everywhere :|
  # @TODO Add following properties: found?, count
  metadata:
    description: |
      A JSON encoded group metadata object, if string format is used or in case of group directory has been provided. 
      Else an JSON encoded array of group metadata object

runs:
  using: 'node20'
  main: 'dist/index.js'
